import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import {Account} from '../components'
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'


import { getStoryblokApi } from "@storyblok/react"

// export async function getStaticProps() {
//   // home is the default slug for the homepage in Storyblok
//   let slug = "home";
 
//   // load the draft version
//   let sbParams = {
//     version: "draft", // or 'published'
//   };
 
//   const storyblokApi = getStoryblokApi();
//   let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);
 
//   console.log(data)

//   return {
//     props: {
//       story: data ? data.story : false,
//       key: data ? data.story.id : false,
//     },
//     revalidate: 3600, // revalidate every hour
//   };
// }

export const getStaticProps: GetStaticProps = async (context) => {
  // home is the default slug for the homepage in Storyblok
  let slug = "home";
 
  // load the draft version
  let sbParams = {
    version: "draft", // or 'published'
  };
 
  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);
 
  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
    revalidate: 3600, // revalidate every hour
  };
}



const Home = (props: any) => {
  const session = useSession()
  const supabase = useSupabaseClient()


  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
              <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
      {!session ? (
        <Auth 
        supabaseClient={supabase} 
        appearance={{ theme: ThemeSupa }} 
        theme="dark" />
      ) : (

        <h1>Hi mom!</h1>

      )}
    </div>
  )
}

export default Home

